### ISSUE TITLE
Mapa con puntos de encuentro

### ISSUE THREAD

**Issue by maariacasasola** [maariacasasola/ISPP2021#43]

**Comment by moicalcob** [comment]
Para dar la tarea por finalizada, tienen que estar las siguientes cosas:

- [ ] Poder mostrar google maps en el frontend, pedirme API Key de Gmaps
- [ ] Poder añadir marcadores a google maps (Mirar api de gmaps for javascript y objeto Marker)
- [ ] Poder traer todos los puntos de encuentro del backend
- [ ] Poder mostrar info rápida sobre el mapa de un punto de encuentro
- [ ] Poder filtrar los puntos de encuentro
